db:
  dsn: "root@/drcash"
  service: "lead"
  event_store: "tracking_lead_log"
services:
  - name: "crm"
    access_token: "111111111"
    url: "v1/crm"

  - name: "order"
    url: "v1/crm"
    access_token: "222222222"
